In [1]:
import numpy as np

In [33]:
a = np.random.rand(4,2)
a
# b = np.array(a, dtype=[('x', None), ('y', None)])

array([[ 0.88212721,  0.03012172],
       [ 0.60416674,  0.44385871],
       [ 0.73260115,  0.21308417],
       [ 0.93525663,  0.16135272]])

In [34]:
a[:,1].argsort()

array([0, 3, 2, 1])

In [39]:
sort = a[:,1].argsort()

In [42]:
a[sort, 0]

array([ 0.88212721,  0.93525663,  0.73260115,  0.60416674])

In [41]:
a

array([[ 0.88212721,  0.03012172],
       [ 0.60416674,  0.44385871],
       [ 0.73260115,  0.21308417],
       [ 0.93525663,  0.16135272]])

In [43]:
a

array([[ 0.88212721,  0.03012172],
       [ 0.60416674,  0.44385871],
       [ 0.73260115,  0.21308417],
       [ 0.93525663,  0.16135272]])

In [49]:
a[:, :] = 'a'

ValueError: could not convert string to float: a

In [50]:
a

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [46]:
class Test():
    def __init__(self):
        self.attr = 1

In [47]:
a[:, :] = Test()

AttributeError: Test instance has no attribute '__float__'

In [62]:
c = np.ndarray(shape=(2,2), dtype=[('strat', object), ('score', int)])

In [65]:
c

array([[(None, 0), (None, 0)],
       [(None, 0), (None, 0)]], 
      dtype=[('strat', 'O'), ('score', '<i8')])

In [71]:
t =  Test()

In [73]:
c[:,0] = Test

ValueError: Setting void-array with object members using buffer.

In [87]:
import pandas as pd

In [89]:
a = np.zeros((2,2))

In [90]:
df = pd.DataFrame(np.zeros((2,2)), columns = ['strat', 'score'])

In [91]:
df

strat  score
0    0.0    0.0
1    0.0    0.0

In [96]:
df.ix[0, 'strat'] = 0

In [97]:
df

strat  score
0     0    0.0
1     0    0.0

In [103]:
df.ix[: , 'strat'] = df.ix[: , 'strat'].apply(lambda x:Test())

In [104]:
df

strat  score
0  <__main__.Test instance at 0x108c5ef80>    0.0
1  <__main__.Test instance at 0x108c5efc8>    0.0

In [105]:
df.ix[0, 'score'] = 1

In [106]:
df

strat  score
0  <__main__.Test instance at 0x108c5ef80>    1.0
1  <__main__.Test instance at 0x108c5efc8>    0.0

In [111]:
df.sort_values(by='score', ascending=True).ix[0,'strat']

<__main__.Test instance at 0x108c5ef80>

In [114]:
fun = lambda x:x+1
df['strat'] = df['score'].apply(fun)

In [115]:
df

strat  score
0    2.0    1.0
1    1.0    0.0

In [117]:
df.sort_values(by='score', ascending=False).ix[:1, 'strat']

0    2.0
1    1.0
Name: strat, dtype: float64

In [118]:
def add(a,b):
    return a+b

In [119]:
parents = df.sort_values(by='score', ascending=False).ix[:1, 'strat']

In [120]:
add(*parents)

3.0

In [125]:
df

strat  score
0    2.0    1.0
1    1.0    0.0

In [128]:
df.append({'strat': 4, 'score': 0}, ignore_index=True)

strat  score
0    2.0    1.0
1    1.0    0.0
2    4.0    0.0

In [129]:
df['score'].max()

1.0

In [130]:
df

strat  score
0    2.0    1.0
1    1.0    0.0

In [131]:
df.ix[2] = (3,4)

In [132]:
df

strat  score
0    2.0    1.0
1    1.0    0.0
2    3.0    4.0

In [133]:
df.ix[7] = (3,4)

In [134]:
df

strat  score
0    2.0    1.0
1    1.0    0.0
2    3.0    4.0
7    3.0    4.0

In [144]:
df.ix[4] = (5,6)

In [147]:
df.shape[0]

5

In [148]:
df

strat  score
0    2.0    1.0
1    1.0    0.0
2    3.0    4.0
7    5.0    6.0
4    5.0    6.0

In [149]:
df.ix[:4]

strat  score
0    2.0    1.0
1    1.0    0.0
2    3.0    4.0
7    5.0    6.0
4    5.0    6.0

In [154]:
df.ix[:2, 'score']

0    1.0
1    0.0
2    4.0
Name: score, dtype: float64